# Correct Netlify build settings
[build]
  # Set the base directory to where your package.json is
  base = "1rfp-app"

  # Set the publish directory to what Vite builds (relative to the base)
  publish = "dist"

  # The command to build your site
  command = "npm run build"